spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:11521/orcdc
    username: C##PFM_MAV
    password: password
    hikari:
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimumIdle: 2
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
  application:
    name: promo-worker-notification
  flyway:
    table: schema_version_pfm_promo_batch
    schemas: ${spring.datasource.main.username}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.main.url}
    user: ${spring.datasource.main.username}
    password: ${spring.datasource.main.password}
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
      acks: 0
      batch-size: 16384
      client-id: ${spring.application.name}
      retries: 1
      retry-backoff-ms: 1000
      request-timeout-ms: 30000
      max-block-ms: 60000
    topic: blast-promo

logging:
  level:
    root: INFO
    id.co.bni.maverick: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    reactor.netty.http.client: DEBUG
    org.hibernate.orm.jdbc.bind: trace
  pattern:
    level: "%5p [appName=${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
